name: dasd

on: 
  pull_request:
    branches:
      - development
      - master  # Run only for pull requests targeting the develop and master branch
    types:
      - synchronize # Trigger when commits are added to the pull request
      - opened # Trigger when a pull request is first opened
      - reopened # Trigger when a previously closed pull request is reopened

jobs:
  build:
    name: "Build Project"
    runs-on: ubuntu-latest

    steps: 
      - name: Send HTTP request to download artifact
        id: request
        uses: tyrrrz/action-http-request@master
        with:
          url: https://api.github.com/repos/Kommunicate-io/Kommunicate-Android-Chat-SDK/actions/artifacts/2355441843
          method: GET
          headers: |
            Authorization: token ${{ secrets.DOWNLOAD_TOKEN }}
            User-Agent: github-actions
          retry-count: 3
          retry-delay: 500

      - name: Print outputs
        run: |
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"
          echo "Headers: ${{ steps.request.outputs.headers }}"
          echo "Body: ${{ steps.request.outputs.body }}"
          echo "Artifact downloaded successfully as artifact.zip"
          # Optional: Save the body (artifact) to a file if it is binary content
          echo "${{ steps.request.outputs.body }}" > artifact.zip