name: dasd

on: 
  pull_request:
    branches:
      - development
      - master  # Run only for pull requests targeting the develop and master branch
    types:
      - synchronize # Trigger when commits are added to the pull request
      - opened # Trigger when a pull request is first opened
      - reopened # Trigger when a previously closed pull request is reopened

jobs:
  build:
    name: "Build Project"
    runs-on: ubuntu-latest

    steps: 
      - name: Get Artifact URL
        run:|
            response = $(curl -H "Authorization: token ${{ secrets.DOWNLOAD_TOKEN }}" -L "https://api.github.com/repos/Kommunicate-io/Kommunicate-Android-Chat-SDK/actions/artifacts/2355441843" -o artifact.zip)
            echo "response from curl= $response"